
import java.util.Random;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TERE
 */
public class ejer4_3 extends javax.swing.JFrame {
    Random rand = new Random();
    List <String> pal = new ArrayList<String>(Arrays.asList("cerillas", "patrulla", "papel", "azor", "alerones", "conversar", "sollozo", "manzana"));
    String adiv = pal.get(rand.nextInt(pal.size()));
    int intentos = 5, cont = adiv.length();

    /**
     * Creates new form ejer4_3
     */
    public ejer4_3() {
        initComponents();
         txt_intentos.setText(Integer.toString(this.intentos));
        for(int i=0; i<this.adiv.length() - 1; i++){
            txt_adivinar.setText(txt_adivinar.getText() + "_ ");
        }
        txt_adivinar.setText(txt_adivinar.getText() + "_");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_introducir = new javax.swing.JTextField();
        btn_introcaracter = new javax.swing.JButton();
        txt_aciertos = new javax.swing.JTextField();
        lbl_aciertos = new javax.swing.JLabel();
        txt_fallos = new javax.swing.JTextField();
        lbl_fallos = new javax.swing.JLabel();
        txt_adivinar = new javax.swing.JTextField();
        lbl_adivinar = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        txt_intentos = new javax.swing.JTextField();
        lbl_intentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_introducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_introducirActionPerformed(evt);
            }
        });

        btn_introcaracter.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        btn_introcaracter.setForeground(new java.awt.Color(0, 0, 255));
        btn_introcaracter.setText("introducir caracter");
        btn_introcaracter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_introcaracterActionPerformed(evt);
            }
        });

        txt_aciertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_aciertosActionPerformed(evt);
            }
        });

        lbl_aciertos.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lbl_aciertos.setForeground(new java.awt.Color(0, 0, 255));
        lbl_aciertos.setText("    aciertos");

        txt_fallos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fallosActionPerformed(evt);
            }
        });

        lbl_fallos.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lbl_fallos.setForeground(new java.awt.Color(0, 0, 255));
        lbl_fallos.setText("fallos");

        txt_adivinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adivinarActionPerformed(evt);
            }
        });

        lbl_adivinar.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lbl_adivinar.setForeground(new java.awt.Color(0, 0, 255));
        lbl_adivinar.setText("palabra a adivinar");

        btn_salir.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(51, 51, 255));
        btn_salir.setText("salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        txt_intentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_intentosActionPerformed(evt);
            }
        });

        lbl_intentos.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lbl_intentos.setForeground(new java.awt.Color(0, 0, 255));
        lbl_intentos.setText("intentos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_adivinar, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(txt_fallos)
                    .addComponent(txt_aciertos)
                    .addComponent(txt_introducir)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_intentos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_intentos)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_aciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fallos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_salir)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_adivinar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_introcaracter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txt_introducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_introcaracter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_aciertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_aciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fallos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_fallos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_adivinar)
                    .addComponent(lbl_adivinar, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salir)
                    .addComponent(txt_intentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_intentos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_introducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_introducirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_introducirActionPerformed

    private void btn_introcaracterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_introcaracterActionPerformed
        // TODO add your handling code here:
        String intr_texto = txt_introducir.getText();
        String logradas = txt_aciertos.getText();
        String erroneas = txt_fallos.getText();
        boolean bandera_existe = false, acierto = false;
        char caracter = intr_texto.charAt(0);
            char car = Character.toLowerCase(caracter);
            for(int i=0; i<logradas.length(); i++){ 
                if(car == logradas.charAt(i)){
                    bandera_existe= true;
                    break;
            }
            if (!bandera_existe){
                for (int j=0; i<erroneas.length(); j++){ 
                    if (car == erroneas.charAt(j)){
                        bandera_existe = true;
                        break;
                    }
                }
            }
            if(!bandera_existe){
                for(int j=0; i<this.adiv.length(); j++)
                    if(car == this.adiv.charAt(j)){
                        acierto = true;
                        break;
                    }
                if(acierto){
                    logradas = txt_aciertos.getText() + car;
                    txt_aciertos.setText(logradas);
                }
                else{
                    txt_fallos.setText(txt_fallos.getText() + car);
                    this.intentos--;
                    txt_intentos.setText(Integer.toString(this.intentos));
                    if(this.intentos == 0){
                        System.exit(0);
                    }
                }
                
                if(acierto){
                    boolean posicion = false;
                    int cont = this.adiv.length();
                    txt_adivinar.setText("");
                    for(int k=0; i<this.adiv.length(); k++){
                        posicion = false;
                        for(int j=0; j<logradas.length(); j++){
                            if(this.adiv.charAt(k) == adiv.charAt(j)){
                                txt_adivinar.setText(txt_adivinar.getText() + this.adiv.charAt(i) + "  ");
                                cont--;
                                posicion = true;
                            }
                        }
                        if(!posicion){
                            txt_adivinar.setText(txt_adivinar.getText() + "_  ");
                        }
                    }
                   
                }
            }
        }
        
       
    }//GEN-LAST:event_btn_introcaracterActionPerformed

    private void txt_aciertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_aciertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_aciertosActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_fallosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fallosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fallosActionPerformed

    private void txt_adivinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adivinarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adivinarActionPerformed

    private void txt_intentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_intentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_intentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejer4_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejer4_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejer4_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejer4_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejer4_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_introcaracter;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lbl_aciertos;
    private javax.swing.JLabel lbl_adivinar;
    private javax.swing.JLabel lbl_fallos;
    private javax.swing.JLabel lbl_intentos;
    private javax.swing.JTextField txt_aciertos;
    private javax.swing.JTextField txt_adivinar;
    private javax.swing.JTextField txt_fallos;
    private javax.swing.JTextField txt_intentos;
    private javax.swing.JTextField txt_introducir;
    // End of variables declaration//GEN-END:variables
}
