import java.util.Random;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.swing.DefaultListModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TERE
 */
public class Ejercicio4_6 extends javax.swing.JFrame {
    private List <Integer> lista = new ArrayList<Integer>();
    private DefaultListModel model = new DefaultListModel<>();

    /**
     * Creates new form Ejercicio4_6
     */
    public Ejercicio4_6() {
        initComponents();
        this.ls_mostrar.setModel (new DefaultListModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_introducir = new javax.swing.JTextField();
        btn_añadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ls_mostrar = new javax.swing.JList<>();
        btn_duplicado = new javax.swing.JButton();
        btn_limpiardatos = new javax.swing.JButton();
        btn_aleatorios = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        txt_duplicados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_introducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_introducirActionPerformed(evt);
            }
        });

        btn_añadir.setText("añadir");
        btn_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirActionPerformed(evt);
            }
        });

        ls_mostrar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ls_mostrar);

        btn_duplicado.setText("comprobar duplicado");
        btn_duplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_duplicadoActionPerformed(evt);
            }
        });

        btn_limpiardatos.setText("limpiar datos");
        btn_limpiardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiardatosActionPerformed(evt);
            }
        });

        btn_aleatorios.setText("aleatorios");
        btn_aleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aleatoriosActionPerformed(evt);
            }
        });

        btn_salir.setText("salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_salir)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_introducir, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(btn_añadir))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_duplicado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_duplicados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_aleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btn_limpiardatos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_introducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_añadir))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_duplicado)
                    .addComponent(btn_aleatorios)
                    .addComponent(txt_duplicados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_limpiardatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_salir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirActionPerformed
        // TODO add your handling code here:
        try{
            Integer numero = Integer.parseInt(txt_introducir.getText());
            txt_introducir.setText("");
            this.lista.add(numero);
            DefaultListModel modelo = (DefaultListModel) ls_mostrar.getModel();
            modelo.addElement(numero);
    
        }catch(NumberFormatException e){
            txt_introducir.setText("Introduce un número entero");
        }   
    }//GEN-LAST:event_btn_añadirActionPerformed

    private void txt_introducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_introducirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_introducirActionPerformed

    private void btn_limpiardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiardatosActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) ls_mostrar.getModel();
        this.lista.clear();
        modelo.clear();
        txt_duplicados.setText("");
        txt_introducir.setText("");
    }//GEN-LAST:event_btn_limpiardatosActionPerformed

    private void btn_duplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_duplicadoActionPerformed
        // TODO add your handling code here:
        boolean repetido = false;
        for(int i=0; i<this.lista.size()-1; i++){
            if(this.lista.get(i)==this.lista.get(i+1)){
                repetido=true;
                break;
            }
        }
        if(repetido) txt_duplicados.setText("S");
        else txt_duplicados.setText("N");
    }//GEN-LAST:event_btn_duplicadoActionPerformed

    private void btn_aleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aleatoriosActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();
        List <Integer> sin_duplicados = new ArrayList<Integer>();
        int numero = rand.nextInt(6);
        sin_duplicados.add(numero);
        DefaultListModel modelo = (DefaultListModel) ls_mostrar.getModel();
        modelo.clear();
        modelo.addElement(numero);
        while(sin_duplicados.size() < 20){
            while(sin_duplicados.contains(numero)){
                numero = rand.nextInt(100);
            }
            sin_duplicados.add(numero);
            modelo.addElement(numero);      
        }        
    }//GEN-LAST:event_btn_aleatoriosActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio4_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aleatorios;
    private javax.swing.JButton btn_añadir;
    private javax.swing.JButton btn_duplicado;
    private javax.swing.JButton btn_limpiardatos;
    private javax.swing.JButton btn_salir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> ls_mostrar;
    private javax.swing.JTextField txt_duplicados;
    private javax.swing.JTextField txt_introducir;
    // End of variables declaration//GEN-END:variables
}
