import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import java.util.Collection;
import java.util.Comparator;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TERE
 */
public class ejercicio4_4 extends javax.swing.JFrame {
    private List <Integer> lista = new ArrayList<Integer>();

    /**
     * Creates new form ejercicio4_4
     */
    public ejercicio4_4() {
        initComponents();
        this.ls_recibe.setModel(new DefaultListModel());
        this.ls_elimina.setModel(new DefaultListModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txt_insertar = new javax.swing.JTextField();
        btn_insertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ls_recibe = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ls_elimina = new javax.swing.JList<>();
        btn_eliminarextremos = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_media = new javax.swing.JButton();
        txt_media = new javax.swing.JTextField();
        txt_mostrar = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_insertarActionPerformed(evt);
            }
        });

        btn_insertar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_insertar.setForeground(new java.awt.Color(0, 0, 255));
        btn_insertar.setText("insertar");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });

        ls_recibe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ls_recibe);

        ls_elimina.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ls_elimina);

        btn_eliminarextremos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_eliminarextremos.setForeground(new java.awt.Color(51, 51, 255));
        btn_eliminarextremos.setText("eliminar_extremos");
        btn_eliminarextremos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarextremosActionPerformed(evt);
            }
        });

        btn_salir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(0, 0, 255));
        btn_salir.setText("salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_media.setForeground(new java.awt.Color(51, 51, 255));
        btn_media.setText("media");
        btn_media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mediaActionPerformed(evt);
            }
        });

        txt_media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mediaActionPerformed(evt);
            }
        });

        txt_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(txt_mostrar)
                    .addComponent(txt_insertar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_insertar)
                            .addComponent(btn_eliminarextremos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_media, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_media))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btn_salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_insertar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_media)
                            .addComponent(txt_media, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(btn_eliminarextremos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir)))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_insertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_insertarActionPerformed

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
        // TODO add your handling code here:
        try{
            this.lista.add(Integer.parseInt(txt_insertar.getText()));
            DefaultListModel modelo = (DefaultListModel) ls_recibe.getModel();
            modelo.clear();
            for (Integer elemento : this.lista) {
                modelo.addElement(elemento);
            }
        }catch (NumberFormatException e){
            
        }
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void btn_eliminarextremosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarextremosActionPerformed
        // TODO add your handling code here:
        if(this.lista.size()< 4){
            txt_mostrar.setText(" debe insertar al menos 4 elemetos" );
           
        }else{
            Comparator<? super Integer> c = null;
            this.lista.sort(c);
            this.lista.remove(0);
            this.lista.remove(this.lista.size() - 1);
            float suma = 0;
            DefaultListModel modelo = (DefaultListModel) ls_elimina.getModel();
            modelo.clear();
            for (Integer elemento : this.lista){
                modelo.addElement(elemento);
                suma += elemento;
            }
            
          
        }
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio4_4().setVisible(true);
            }
        });
    }//GEN-LAST:event_btn_eliminarextremosActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mediaActionPerformed
        // TODO add your handling code here:
         float suma = 0;
            DefaultListModel modelo = (DefaultListModel) ls_elimina.getModel();
            modelo.clear();
            for (Integer elemento : this.lista){
                modelo.addElement(elemento);
                suma += elemento;
            }
        txt_media.setText(" " +(float) suma/this.lista.size());
    }//GEN-LAST:event_btn_mediaActionPerformed

    private void txt_mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mediaActionPerformed

    private void txt_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mostrarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminarextremos;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JButton btn_media;
    private javax.swing.JButton btn_salir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> ls_elimina;
    private javax.swing.JList<String> ls_recibe;
    private javax.swing.JTextField txt_insertar;
    private javax.swing.JTextField txt_media;
    private javax.swing.JTextField txt_mostrar;
    // End of variables declaration//GEN-END:variables
}
