/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejer2_2;

import javax.swing.JTextField;

/**
 *
 * @author TERE
 */
public class Ejercicio2_15 extends javax.swing.JFrame {
    int cociente=0;

    /**
     * Creates new form Ejercicio2_15
     */
    public Ejercicio2_15() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_dividendo = new javax.swing.JTextField();
        btn_dividendo = new javax.swing.JButton();
        txt_divisor = new javax.swing.JTextField();
        btn_divisor = new javax.swing.JButton();
        txt_cociente = new javax.swing.JTextField();
        lbl_cociente = new javax.swing.JLabel();
        txt_resto = new javax.swing.JTextField();
        lbl_resto = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_resultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_dividendo.setText("dividendo");
        btn_dividendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dividendoActionPerformed(evt);
            }
        });

        txt_divisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_divisorActionPerformed(evt);
            }
        });

        btn_divisor.setText("divisor");
        btn_divisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisorActionPerformed(evt);
            }
        });

        lbl_cociente.setText("cociente");

        lbl_resto.setText("resto");

        btn_salir.setText("salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_limpiar.setText("limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_resultado.setText("resultado");
        btn_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lbl_cociente)
                        .addGap(65, 65, 65)
                        .addComponent(lbl_resto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_salir)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_cociente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_resto, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                    .addComponent(txt_divisor)
                                    .addComponent(txt_dividendo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_dividendo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_divisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_limpiar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btn_resultado)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dividendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dividendo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_divisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_divisor))
                .addGap(18, 18, 18)
                .addComponent(btn_resultado)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cociente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_resto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cociente)
                    .addComponent(lbl_resto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btn_salir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dividendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dividendoActionPerformed
        // TODO add your handling code here:
        String divi = new String();
        try{
            divi = txt_dividendo.getText();
            int dividendo = Integer.parseInt(divi);
            
            
        } catch(NumberFormatException e){
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_btn_dividendoActionPerformed

    private void btn_divisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisorActionPerformed
        // TODO add your handling code here:
        String div = new String();
        try{
            div = txt_dividendo.getText();
            int divisor = Integer.parseInt(div);
            
        } catch(NumberFormatException e){
            e.printStackTrace();
        }
       
       
        
        
    }//GEN-LAST:event_btn_divisorActionPerformed

    private void txt_divisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_divisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_divisorActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        txt_dividendo.setText(" ");
        txt_divisor.setText(" ");
        txt_cociente.setText(" ");
        txt_resto.setText(" ");
        
        
        
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultadoActionPerformed
        // TODO add your handling code here:
        String divi = new String();
        try{
            divi = txt_dividendo.getText();
            int dividendo = Integer.parseInt(divi);
            String div = txt_divisor.getText();
            int divisor = Integer.parseInt(div);
            
         
            while ( dividendo > 0)
            {
                this.cociente ++;
                dividendo = dividendo - divisor;                
            }
            txt_cociente.setText(txt_cociente.getText()+Integer.toString(this.cociente) + " ");
            txt_resto.setText(txt_resto.getText()+Integer.toString(-dividendo) + " ");
            
        } catch(NumberFormatException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2_15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dividendo;
    private javax.swing.JButton btn_divisor;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_resultado;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lbl_cociente;
    private javax.swing.JLabel lbl_resto;
    private javax.swing.JTextField txt_cociente;
    private javax.swing.JTextField txt_dividendo;
    private javax.swing.JTextField txt_divisor;
    private javax.swing.JTextField txt_resto;
    // End of variables declaration//GEN-END:variables
}
